language: rust
dist: trusty
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
before_script: ((cargo install cargo-travis &&  cargo install rustfmt-nightly) || true)
script:
- cargo clean
- cargo build 
- cargo test
after_success: |
 if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
