[package]
name = "lexer"
version = "0.1.0"
authors = ["Lenard Pratt <striderman34@gmail.com>"]
[features]
default = []

[dependencies]
clippy = {version = "*", optional = true}

[dev-dependencies]
pretty_assertions = "0.4.0"