[package]
name = "vm"
version = "0.1.0"
authors = ["Lenard Pratt <striderman34@gmail.com>"]


edition='2018'

[dependencies]
util = {path = "../util"}
nom = "^4.0"
opcode = {path="../opcode"}
rand = "*"

[features]
debug = []
stack = ["debug"]
default = []

