[package]
name = "tox"
version = "0.2.0"
authors = ["Lenard Pratt <striderman34@gmail.com>"]
[features]
default = []
debug = ["vm/debug"]
graphviz = ["frontend/graphviz"]
prettytable = ["ir/prettytable"]
dom = ["ir/dom"]
live_ranges = ["ir/live_ranges"]
live_out = ["ir/live_out"]
# debug = ["vm/debug"]  # Enable debug statements within the vm

[dependencies]
util = {path = "../util"}
syntax = {path = "../syntax"}
ir = {path="../ir"}
frontend = {path = "../frontend"}
vm = {path="../vm"}
structopt = "0.1.6"
structopt-derive = "0.1.6"
clippy = {version = "*", optional = true}
fnv = "*"


[[test]]
name ="test_runner"
path ="../tests/test_runner.rs"
harness = false


[dev-dependencies]
walkdir = "2"
ansi_term = "0.10"
tempfile = "3"