[package]
name = "tox"
version = "0.2.0"
authors = ["Lenard Pratt <striderman34@gmail.com>"]
[features]
default = []
debug = ["vm/debug"] # Enable debug statements within the vm

[dependencies]
util = {path = "../util"}
syntax = {path = "../syntax"}
frontend = {path = "../frontend"}
interpreter = {path ="../interpreter"}
vm = {path="../vm"}
structopt = "0.1.6"
structopt-derive = "0.1.6"
clippy = {version = "*", optional = true}
fnv = "*"
