[package]
name = "codegen"
version = "0.1.0"
authors = ["Lenard Pratt <striderman34@gmail.com>"]

[dependencies]
syntax ={path="../syntax"}
util ={path="../util"}


[dependencies.vm]
path ="../vm"
features = ["debug"]